/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.emp.gl.heure;

import java.beans.PropertyChangeEvent;
import org.emp.gl.action.WatchAction;
import org.emp.gl.core.lookup.Lookup;
import org.emp.gl.timer.service.TimerChangeListener;
import org.emp.gl.timer.service.TimerService;

/**
 *
 * @author younes
 */
public class Heure extends javax.swing.JFrame  implements TimerChangeListener{

    /**
     * Creates new form Heure
     */
    public Heure() {
        initComponents();
       TimerService ts = Lookup.getInstance().getService(TimerService.class);
       
            //TimerService ts = Lookup.getInstance().getService(.class);
        this.dixSecond.setText( Integer.toString(ts.getDixiemeDeSeconde()) );
        this.second.setText( Integer.toString(ts.getSecondes()) );
        this.minute.setText( Integer.toString(ts.getMinutes()) );
        this.houre.setText( Integer.toString(ts.getHeures()) );  
        
        /*
        System.out.println(ts.getDixiemeDeSeconde());
        System.out.println(ts.getSecondes());
        System.out.println(ts.getMinutes());
        System.out.println(ts.getHeures());*/
      
        
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        houre = new javax.swing.JLabel();
        minute = new javax.swing.JLabel();
        second = new javax.swing.JLabel();
        dixSecond = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        houre.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        houre.setText("00");

        minute.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        minute.setText("00");

        second.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        second.setText("00");

        dixSecond.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        dixSecond.setText("00");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText(":");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText(":");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setText(":");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(houre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(minute)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(second)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dixSecond)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dixSecond)
                    .addComponent(minute)
                    .addComponent(houre)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(second))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        System.out.println(" hi  ");
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Heure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Heure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Heure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Heure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Heure().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dixSecond;
    private javax.swing.JLabel houre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel minute;
    private javax.swing.JLabel second;
    // End of variables declaration//GEN-END:variables

@Override
    public void propertyChange(PropertyChangeEvent pce) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        TimerService ts = Lookup.getInstance().getService(TimerService.class);
        if(pce.getPropertyName().equals( TimerChangeListener.DIXEME_DE_SECONDE_PROP)){
            

            /*System.out.println("" + ts.getHeures() + ":" + ts.getMinutes() + ":"
                    + ts.getSecondes() + "," + pce.getNewValue());*/
            //this.dixSecond.setText(Integer.toString(ts.getDixiemeDeSeconde()));
             this.dixSecond.setText(pce.getNewValue().toString());
        }
        else if(pce.getPropertyName() .equals( TimerChangeListener.SECONDE_PROP)){
            //TimerService ts = Lookup.getInstance().getService(TimerService.class);
            
           // this.second.setText( Integer.toString(ts.getSecondes()) );
             this.second.setText(pce.getNewValue().toString());
            //System.out.println(ts.getDixiemeDeSeconde());
        }
        else if(pce.getPropertyName().equals(TimerChangeListener.MINUTE_PROP)){
           // TimerService ts = Lookup.getInstance().getService(TimerService.class);

          // this.minute.setText( Integer.toString(ts.getMinutes()) );
            this.minute.setText(pce.getNewValue().toString());
           //System.out.println(ts.getDixiemeDeSeconde());
        }
        else if (pce.getPropertyName().equals(TimerChangeListener.HEURE_PROP)){
            //TimerService ts = Lookup.getInstance().getService(TimerService.class);

            //this.houre.setText(Integer.toString(ts.getHeures()));
             this.houre.setText(pce.getNewValue().toString());
            //this.houre.setText(" hour");
            System.out.println(ts.getHeures()+"      ");
           // System.out.println(" hour "+ ts.getHeures());
        }
        else{
            System.out.println(" property change error !! ");
        }
    }
}
